---
deployment:
  tasks:
    - export DEPLOYPATH=/home-550/tripop/public_html/www/
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f about.html $DEPLOYPATH
    - /bin/cp -f paybill.html $DEPLOYPATH
    - /bin/cp -f policy.html $DEPLOYPATH
    - /bin/cp -f tti-ga.html $DEPLOYPATH
    - /bin/cp -f tti-nvr.html $DEPLOYPATH
    - /bin/cp -f send-quote.php $DEPLOYPATH
    - /bin/cp -f tti-voip.html $DEPLOYPATH
    - /bin/cp -f send-voip-quote.php $DEPLOYPATH
    - /bin/cp -f frigate-clean-view.user.css $DEPLOYPATH
    - /bin/cp -f frigate-style-handler.php $DEPLOYPATH
    - /bin/cp -f .htaccess $DEPLOYPATH
